import {defaults,ranges,genres,scenes,presets,clamp,tapTempo,spotifyEmbed,esc} from './model.mjs';
import {AudioDeck} from './audio.mjs';
import {Renderer} from './render.mjs';
import {projects} from './projects.mjs';
const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];
const deck=new AudioDeck(), reduced=matchMedia('(prefers-reduced-motion: reduce)');
const state={...defaults,scene:0};let moving=!reduced.matches,dirty=true,visible=true,burst=0,renderer=null,time=0,renderTime=0,last=0,lastUI=0,media=null,mediaURL=null,loadVersion=0,noticeTimer,previousFocus=null;
let bypass={space:false,glitch:false,feedback:false,modulation:false};
function notice(text){$('#notice').textContent=text;$('#notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').hidden=true,7000);}
function fail(text){notice(text);$('#gpu').textContent='GRAPHICS LIMITED';if(!renderer||renderer.lost){$('#fallback').hidden=false;$('#resolution').textContent='NO WEBGL';moving=false;$('#motion-status').textContent='GRAPHICS UNAVAILABLE';$$('.effects input,.effects button,#clips button,#media-clips button,#mix,#clear-media,#motion').forEach(el=>el.disabled=true);}}
const controlGroups={
 'glitch-controls':[['mosh','Datamosh','Temporal block smearing'],['sorting','Pixel sorting','16 px blocks · luminance order'],['threshold','Sort threshold','Only sort pixels above this luminance'],['artifacts','Artifacting','RGB separation + macroblocks'],['feedback','Feedback','Persistent frame history']],
 'space-controls':[['displacement','Displacement'],['zoom','Scale'],['rotation','Rotation'],['hue','Hue shift'],['speed','Motion speed']],
 'react-controls':[['react','Audio → motion']]
};
function format(key,value){return ['rotation','hue'].includes(key)?`${Math.round(value)}°`:['zoom','speed'].includes(key)?`${value.toFixed(2)}×`:`${Math.round(value*100)}%`;}
for(const [container,items] of Object.entries(controlGroups)){$('#'+container).innerHTML=items.map(([key,label,hint])=>`<label class="control" for="${key}"><span class="control-title">${label}<output id="${key}-value" for="${key}">${format(key,state[key])}</output></span><input id="${key}" data-param="${key}" type="range" min="${ranges[key][0]}" max="${ranges[key][1]}" step="${['rotation','hue'].includes(key)?1:.01}" value="${state[key]}">${hint?`<small class="hint">${hint}</small>`:''}</label>`).join('');}
function update(){for(const key of Object.keys(ranges)){const input=$('#'+key);if(input)input.value=state[key];const output=$('#'+key+'-value');if(output)output.value=format(key,state[key]);}$('#mirror').checked=state.mirror;dirty=true;}
$$('[data-param]').forEach(input=>input.addEventListener('input',()=>{const key=input.dataset.param;state[key]=clamp(input.value,...ranges[key]);$('#'+key+'-value').value=format(key,state[key]);$$('[data-preset]').forEach(b=>b.setAttribute('aria-pressed','false'));dirty=true;}));
$('#presets').innerHTML=Object.keys(presets).map((key,i)=>`<button data-preset="${key}" aria-pressed="${i===0}">${{clean:'Clean',fracture:'Break',sort:'Sort',echo:'Echo',acid:'Acid'}[key]}</button>`).join('');
$$('[data-preset]').forEach(b=>b.addEventListener('click',()=>{const mix=state.mix;Object.assign(state,presets[b.dataset.preset],{mix});$$('[data-preset]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderer?.clear();update();}));
function reset(){const mix=state.mix;Object.assign(state,defaults,{mix});bypass={space:false,glitch:false,feedback:false,modulation:false};syncNodes();renderer?.clear();$$('[data-preset]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.preset==='clean')));update();}
$('#reset').onclick=reset;$('#mirror').onchange=e=>{state.mirror=e.target.checked;dirty=true;};$('#clear-feedback').onclick=()=>{renderer?.clear();dirty=true;notice('Frame history cleared.');};
function setBurst(v){burst=v;$('#mosh-burst').setAttribute('aria-pressed',String(Boolean(v)));dirty=true;}
$('#mosh-burst').onpointerdown=e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);setBurst(1);};for(const name of ['pointerup','pointercancel','lostpointercapture'])$('#mosh-burst').addEventListener(name,()=>setBurst(0));
$('#mosh-burst').addEventListener('keydown',e=>{if([' ','Enter'].includes(e.key)){e.preventDefault();setBurst(1);}});$('#mosh-burst').addEventListener('keyup',()=>setBurst(0));window.addEventListener('blur',()=>setBurst(0));
function effective(){return {...state,...(bypass.space?{zoom:1,rotation:0,hue:0,displacement:0,mirror:false}:{}),...(bypass.glitch?{sorting:0,mosh:0,artifacts:0}:{}),...(bypass.feedback?{feedback:0}:{}),...(bypass.modulation?{react:0}:{})};}
$('#nodes').innerHTML='<button disabled>SOURCE</button>'+[['space','TRANSFORM'],['glitch','GLITCH'],['feedback','FEEDBACK'],['modulation','AUDIO MOD']].map(([key,label])=>`<button data-node="${key}" aria-pressed="true">${label}</button>`).join('');
function syncNodes(){$$('[data-node]').forEach(b=>b.setAttribute('aria-pressed',String(!bypass[b.dataset.node])));for(const key of ['zoom','rotation','hue','displacement'])$('#'+key).disabled=bypass.space;for(const key of ['sorting','threshold','artifacts','mosh'])$('#'+key).disabled=bypass.glitch;$('#mirror').disabled=bypass.space;$('#feedback').disabled=bypass.feedback;$('#react').disabled=bypass.modulation;dirty=true;}
$$('[data-node]').forEach(b=>b.onclick=()=>{bypass[b.dataset.node]=!bypass[b.dataset.node];syncNodes();renderer?.clear();});
function tab(which){for(const name of ['clips','flow']){$('#'+name+'-tab').setAttribute('aria-selected',String(name===which));$('#'+name+'-tab').tabIndex=name===which?0:-1;$('#'+name+'-panel').hidden=name!==which;}}
for(const name of ['clips','flow']){$('#'+name+'-tab').onclick=()=>tab(name);$('#'+name+'-tab').onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const target=e.key==='Home'?'clips':e.key==='End'?'flow':name==='clips'?'flow':'clips';tab(target);$('#'+target+'-tab').focus();}};}
$('#clips').innerHTML=scenes.map((s,i)=>`<button class="clip" data-scene="${i}" aria-pressed="${i===0}"><canvas width="176" height="100" aria-hidden="true"></canvas><span>0${i+1}</span><div class="clip-info"><strong>${s}</strong><small>GENERATIVE / REAL-TIME</small></div></button>`).join('');
function chooseScene(index){state.scene=index;$('#scene-name').textContent=scenes[index].toUpperCase();$('#output-title').textContent=scenes[index];$$('[data-scene]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.scene===index)));dirty=true;}
$$('[data-scene]').forEach(b=>b.onclick=()=>chooseScene(+b.dataset.scene));
$('#media-clips').innerHTML=projects.slice(0,4).map((p,i)=>`<button class="clip" data-media="${p.id}" aria-pressed="false"><div class="clip-placeholder">${['▷','◇','▥','⌁'][i]}</div><span>PROJECT / ${i+1}</span><div class="clip-info"><strong>${esc(p.title)}</strong><small>${p.media.endsWith('mp4')?'VIDEO':'IMAGE'} / LOAD INTO B</small></div></button>`).join('');
// Local visual import never publishes the file or inserts an external source URL.
const importButton=document.createElement('button');importButton.className='quiet';importButton.textContent='↑ Add your own visual';importButton.style.margin='8px 14px';const visualInput=document.createElement('input');visualInput.type='file';visualInput.accept='video/*,image/*';visualInput.hidden=true;$('#clips-panel').append(importButton,visualInput);importButton.onclick=()=>visualInput.click();visualInput.onchange=async()=>{const file=visualInput.files[0];visualInput.value='';if(!file)return;if(file.size>150*1024*1024||! /^(video|image)\//.test(file.type)){notice('Choose an image or video under 150 MB.');return;}const url=URL.createObjectURL(file);await loadMedia(url,file.name,file.type.startsWith('video/'),true);};
function releaseMedia(){if(media){media.pause?.();if(media.tagName==='VIDEO'){media.removeAttribute('src');media.load();}}if(mediaURL)URL.revokeObjectURL(mediaURL);mediaURL=null;media=null;}
async function loadMedia(url,title,video=false,owned=false){const version=++loadVersion;const el=document.createElement(video?'video':'img');if(/^https?:/.test(url)&&new URL(url).origin!==location.origin)el.crossOrigin='anonymous';if(video){el.muted=true;el.loop=true;el.playsInline=true;el.preload='auto';}let timer;const ready=new Promise((resolve,reject)=>{el.addEventListener(video?'loadeddata':'load',resolve,{once:true});el.addEventListener('error',()=>reject(Error('That media could not load or decode. The generated deck is still available.')),{once:true});timer=setTimeout(()=>reject(Error('Media timed out. Try a smaller local file.')),18000);});el.src=url;
 try{await ready;clearTimeout(timer);if(version!==loadVersion){el.pause?.();el.removeAttribute('src');if(owned)URL.revokeObjectURL(url);return;}releaseMedia();media=el;mediaURL=owned?url:null;renderer?.setMedia(el);state.mix=1;$('#mix').disabled=false;$('#clear-media').disabled=false;$('#output-kind').textContent='SOURCE B / '+title;$('#mix').value='1';if(video&&moving)await el.play().catch(()=>notice('Video is loaded; press Visuals to resume playback.'));dirty=true;}catch(e){clearTimeout(timer);el.pause?.();el.removeAttribute('src');if(owned)URL.revokeObjectURL(url);if(version===loadVersion)notice(e.message);}}
$$('[data-media]').forEach(b=>b.onclick=async()=>{const p=projects.find(p=>p.id===b.dataset.media);await loadMedia(p.media,p.title,p.media.endsWith('.mp4'));if(media)$$('[data-media]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});
$('#mix').oninput=e=>{state.mix=clamp(e.target.value);dirty=true;};$('#clear-media').onclick=()=>{loadVersion++;releaseMedia();renderer?.setMedia(null);state.mix=0;$('#mix').value=0;$('#mix').disabled=true;$('#clear-media').disabled=true;$('#output-kind').textContent='SOURCE A / REAL-TIME 3D';$$('[data-media]').forEach(b=>b.setAttribute('aria-pressed','false'));dirty=true;};
function setMotion(value){moving=Boolean(value)&&$('#fallback').hidden;$('#motion').setAttribute('aria-pressed',String(moving));$('#motion').textContent=moving?'Ⅱ Visuals':'▶ Visuals';if(media?.tagName==='VIDEO'){if(moving)media.play().catch(()=>{});else media.pause();}dirty=true;}
setMotion(moving);$('#motion').onclick=()=>setMotion(!moving);reduced.addEventListener('change',e=>{if(e.matches)setMotion(false);});
function audioUI(){$('#play').textContent=deck.running?'Ⅱ':'▶';$('#play').setAttribute('aria-label',deck.running?'Pause session':'Start with sound');$('#music-state').textContent=deck.running?'PLAYING / '+deck.mode.toUpperCase():'READY / SOUND OFF';$('#track-title').textContent=deck.mode==='local'?deck.label:deck.mode==='mic'?'Microphone input':deck.genre.title;$('#track-sub').textContent=deck.mode==='builtin'?deck.genre.name+' · original synthesized demo':deck.mode==='mic'?'Listening locally · never sent to speakers':'Local file · not uploaded';$('#bpm').value=Math.round(deck.bpm);$('#clock-status').textContent=deck.mode==='builtin'?'EXACT BUILT-IN CLOCK':'AUDIO REACTIVE / MANUAL BPM';$('#mic').setAttribute('aria-pressed',String(deck.mode==='mic'&&deck.running));$('#disconnect').hidden=deck.mode==='builtin';$$('[data-genre]').forEach(b=>b.setAttribute('aria-pressed',String(deck.mode==='builtin'&&b.dataset.genre===deck.genre.id)));}
async function play(){try{if(deck.running){deck.mode==='mic'?deck.disconnect():deck.pause();setMotion(false);}else{await deck.start();if(!reduced.matches)setMotion(true);}audioUI();}catch(e){notice(e.message);audioUI();}}
$('#play').onclick=play;$('#genres').innerHTML=genres.map((g,i)=>`<button data-genre="${g.id}" aria-pressed="${i===0}" title="${g.title} · ${g.bpm} BPM">${g.name}</button>`).join('');
$$('[data-genre]').forEach(b=>b.onclick=async()=>{try{await deck.select(b.dataset.genre);if(!reduced.matches)setMotion(true);audioUI();}catch(e){notice(e.message);}});
$('#volume').oninput=e=>{deck.setVolume(e.target.value);$('#mute').setAttribute('aria-pressed',String(deck.volume===0));};let previousVolume=.28;$('#mute').onclick=()=>{if(deck.volume>0){previousVolume=deck.volume;deck.setVolume(0);}else deck.setVolume(previousVolume||.28);$('#volume').value=deck.volume;$('#mute').setAttribute('aria-pressed',String(deck.volume===0));};
$('#bpm').onchange=e=>{deck.setTempo(e.target.value);e.target.value=deck.bpm;dirty=true;};let taps=[];function tap(){const now=performance.now()/1000;if(taps.length&&now-taps.at(-1)>2)taps=[];taps.push(now);taps=taps.slice(-7);const bpm=tapTempo(taps);if(bpm){deck.setTempo(bpm);audioUI();}else notice('Keep tapping for tempo.');}$('#tap').onclick=tap;
$('#local-audio').onclick=()=>$('#audio-file').click();$('#audio-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{await deck.load(file);audioUI();if(!reduced.matches)setMotion(true);}catch(e){notice(e.message);audioUI();}};
$('#mic').onclick=async()=>{try{if(deck.mode==='mic')deck.disconnect();else await deck.microphone();audioUI();}catch(e){notice(e.name==='NotAllowedError'?'Microphone permission was not granted. Built-in music remains available.':e.message);audioUI();}};
$('#disconnect').onclick=()=>{deck.disconnect();audioUI();notice('External audio disconnected. Built-in music is ready.');};
$('#explorer').innerHTML=projects.map((p,i)=>`<button class="explorer-item" data-project="${p.id}"><span>${String(i+1).padStart(2,'0')}</span>${esc(p.title)}</button>`).join('');
$('#projects').innerHTML=projects.map((p,i)=>`<button class="project-card" data-project="${p.id}"><span class="eyebrow">${String(i+1).padStart(2,'0')} / ${esc(p.category)}</span><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p><span>OPEN PROJECT FILE ↗</span></button>`).join('');
function openDialog(id){previousFocus=document.activeElement;$('#'+id).showModal();document.body.style.overflow='hidden';$('#'+id+' [data-close]').focus();}
$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$$('dialog').forEach(d=>d.addEventListener('close',()=>{document.body.style.overflow='';if(d.id==='details')$$('#details video').forEach(v=>v.pause());previousFocus?.focus({preventScroll:true});}));
function project(id,push=true){const p=projects.find(x=>x.id===id);if(!p)return;$('#details-content').innerHTML=`<span class="eyebrow">${esc(p.category)} / ${esc(p.location)}</span><h2 id="details-title">${esc(p.title)}</h2><p>${esc(p.role)}</p><p>${esc(p.description)}</p><div class="case-body">${[['Challenge',p.challenge],['Architecture',p.architecture],['Execution',p.execution]].map(([t,b])=>`<section><h3>${t}</h3><p>${esc(b)}</p></section>`).join('')}</div><div class="taglist">${p.tools.map(t=>`<span>${esc(t)}</span>`).join('')}</div>${p.media.endsWith('mp4')?`<video controls playsinline preload="metadata" src="${esc(p.media)}"></video>`:`<img src="${esc(p.media)}" alt="${esc(p.title)} — original project documentation" loading="lazy">`}<p><a href="${esc(p.media)}" target="_blank" rel="noopener">Open original media ↗</a>${p.link?` &nbsp; · &nbsp; <a href="${esc(p.link)}" target="_blank" rel="noopener">Project website ↗</a>`:''}</p>`;$('#details-content img, #details-content video').addEventListener('error',e=>{e.target.hidden=true;notice('Project media is unavailable in this preview. The original file link is preserved.');},{once:true});if(!$('#details').open)openDialog('details');if(push)history.pushState(null,'','#project/'+p.id);}
$$('[data-project]').forEach(b=>b.onclick=()=>project(b.dataset.project));$('#details').addEventListener('close',()=>{if(location.hash.startsWith('#project/'))history.replaceState(null,'','#work');});function hash(){if(location.hash.startsWith('#project/'))project(location.hash.slice(9),false);else if($('#details').open)$('#details').close();}window.addEventListener('hashchange',hash);hash();
$('#help').onclick=()=>openDialog('guide');$('#spotify').onclick=()=>{deck.disconnect();audioUI();setMotion(false);setBurst(0);openDialog('spotify-room');};$('#spotify-form').onsubmit=e=>{e.preventDefault();const url=spotifyEmbed($('#spotify-url').value);if(!url){$('#spotify-message').textContent='Paste a full https://open.spotify.com/ track, playlist or album link, not a short link.';return;}const frame=document.createElement('iframe');frame.src=url;frame.title='Spotify music player';frame.allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture';frame.loading='eager';$('#spotify-player').replaceChildren(frame);$('#spotify-message').textContent='Spotify player requested. Use Open Spotify if it cannot load. The instrument stays paused; no Spotify signal reaches the effect rack.';};$('#spotify-room').addEventListener('close',()=>{$('#spotify-player').replaceChildren();notice('Spotify closed. Press play to return to the built-in set.');});
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if($('#output').requestFullscreen)await $('#output').requestFullscreen();else notice('Fullscreen is not supported by this browser.');}catch{notice('Fullscreen was not available.');}};
const acceptsKeys=e=>!e.ctrlKey&&!e.metaKey&&!e.altKey&&!e.target.closest('input,textarea,select,[contenteditable=true]')&&!$$('dialog').some(d=>d.open);
document.addEventListener('keydown',e=>{if(!acceptsKeys(e)||e.repeat||(e.code==='Space'&&e.target.closest('button,a')))return;if(e.code==='Space'){e.preventDefault();play();}if(e.key.toLowerCase()==='t')tap();if(e.key.toLowerCase()==='r')reset();if(e.key.toLowerCase()==='m')setBurst(1);if(/^[1-4]$/.test(e.key))chooseScene(+e.key-1);});document.addEventListener('keyup',e=>{if(e.key.toLowerCase()==='m')setBurst(0);});
const meter=$('#spectrum').getContext('2d');let smoothed=[0,0,0];
function loop(now){const delta=Math.min(.05,(now-(last||now))/1000);last=now;if(moving)time+=delta;const audio=deck.sample();if(!audio.active)audio.beat=time*deck.bpm/60;if(moving)renderTime=deck.running&&deck.mode==='builtin'?audio.beat*.5:time;smoothed=audio.bands.map((b,i)=>smoothed[i]+(b-smoothed[i])*.25);audio.bands=smoothed;
 if(renderer&&!renderer.lost&&visible&&(moving||dirty)&&!document.hidden){renderer.render(effective(),renderTime,audio,bypass.glitch?0:burst);dirty=false;}
 if(now-lastUI>95){lastUI=now;$('#timer').textContent=`${String(Math.floor(time/60)).padStart(2,'0')}:${String(Math.floor(time%60)).padStart(2,'0')}`;$('#motion-status').textContent=(!renderer||renderer.lost)?'STATIC PORTFOLIO / GRAPHICS UNAVAILABLE':moving?(deck.running?'LIVE / '+(deck.mode==='builtin'?'BEAT LOCKED':'AUDIO REACTIVE'):'LIVE PREVIEW · SOUND OFF'):'VISUAL MOTION PAUSED';$$('.beat-leds i').forEach((el,i)=>el.classList.toggle('active',(deck.running||moving)&&Math.floor(audio.beat)%4===i));for(const [i,key] of ['low','mid','high'].entries())$('#'+key).textContent=Math.round(smoothed[i]*100);meter.clearRect(0,0,280,26);meter.fillStyle='#b7d992';for(let i=0;i<48;i++){const h=audio.freq?Math.max(1,audio.freq[Math.floor(i/48*230)]/255*24):1;meter.fillRect(i*5.8,26-h,3.4,h);}}
 requestAnimationFrame(loop);
}
try{renderer=new Renderer($('#visual'),fail);for(let i=0;i<4;i++){renderer.clear();renderer.render({...defaults,scene:i},4,{bands:[0,0,0],beat:0});const thumb=$(`[data-scene="${i}"] canvas`);thumb.getContext('2d').drawImage($('#visual'),0,0,thumb.width,thumb.height);}renderer.clear();$('#resolution').textContent=`${renderer.w} × ${renderer.h} / LOCAL RENDER`;new ResizeObserver(()=>{if(renderer&&!renderer.lost){renderer.resize();$('#resolution').textContent=`${renderer.w} × ${renderer.h} / LOCAL RENDER`;dirty=true;}}).observe($('#visual'));new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)dirty=true;}).observe($('#visual'));}catch(e){fail('The 3D engine could not start. Browse your project files below.');console.warn('Visual engine:',e.message);}
window.addEventListener('pagehide',()=>{deck.disconnect();releaseMedia();setMotion(false);});document.addEventListener('visibilitychange',()=>{if(document.hidden){deck.mode==='mic'?deck.disconnect():deck.pause();setMotion(false);audioUI();setBurst(0);}last=0;});
// Read-only diagnostics: no tokens, source audio, or visitor data.
window.liveDiagnostics=()=>({frames:renderer?.frames||0,passes:renderer?.draws||0,webgl:Boolean(renderer&&!renderer.lost),audioRunning:deck.running,audioMode:deck.mode,bpm:deck.bpm,moving,mediaLoaded:Boolean(media),spotifyMounted:Boolean($('#spotify-player iframe')),state:{...state},bypass:{...bypass}});
audioUI();requestAnimationFrame(loop);
