import {clamp,genres,spectrumBands} from './model.mjs';
/** Original procedural demo sketches. No recordings, samples, or external music APIs. */
export class AudioDeck {
 constructor(){this.genre=genres[0];this.bpm=this.genre.bpm;this.mode='builtin';this.running=false;this.volume=.28;this.voices=new Set();this.step=0;this.offset=0;this.generation=0;this.file=null;this.stream=null;}
 ensure(){if(this.ctx)return;const Audio=globalThis.AudioContext||globalThis.webkitAudioContext;if(!Audio)throw Error('Web Audio is unavailable. You can still explore the visuals silently.');this.ctx=new Audio({latencyHint:'interactive'});const c=this.ctx;this.bus=c.createDynamicsCompressor();this.bus.threshold.value=-12;this.bus.knee.value=8;this.bus.ratio.value=10;this.bus.attack.value=.004;this.bus.release.value=.16;this.output=c.createGain();this.output.gain.value=this.volume;this.analyser=c.createAnalyser();this.analyser.fftSize=2048;this.analyser.smoothingTimeConstant=.72;this.silent=c.createGain();this.silent.gain.value=0;this.bus.connect(this.output).connect(c.destination);this.bus.connect(this.analyser).connect(this.silent).connect(c.destination);this.freq=new Uint8Array(this.analyser.frequencyBinCount);this.noise=c.createBuffer(1,c.sampleRate,c.sampleRate);const a=this.noise.getChannelData(0);let s=1447;for(let i=0;i<a.length;i++){s=(s*1664525+1013904223)>>>0;a[i]=s/2147483648-1;}this.media=new AudioElement();this.media.loop=true;this.media.preload='metadata';this.mediaSource=c.createMediaElementSource(this.media);this.mediaSource.connect(this.bus);}
 setVolume(v){this.volume=clamp(v,0,.8);if(this.output)this.output.gain.setTargetAtTime(this.volume,this.ctx.currentTime,.03);}
 setTempo(v){this.bpm=clamp(v,50,200);if(this.running&&this.mode==='builtin'){this.stopVoices();this.step=0;this.origin=this.ctx.currentTime+.06;this.next=this.origin;}else{this.origin=(this.ctx?.currentTime||0);if(this.mode==='local')this.offset=this.media.currentTime;}}
 async start(){this.ensure();const token=++this.generation;await this.ctx.resume();if(token!==this.generation)return;if(this.mode==='local'){await this.media.play();if(token!==this.generation){this.media.pause();return;}}this.running=true;if(this.mode==='builtin'){this.origin=this.ctx.currentTime+.07;this.next=this.origin;this.step=0;clearInterval(this.timer);this.schedule();this.timer=setInterval(()=>this.schedule(),25);}}
 pause(){this.generation++;this.running=false;clearInterval(this.timer);this.stopVoices();this.media?.pause();}
 stopVoices(){for(const voice of this.voices){try{voice.stop();}catch{}}this.voices.clear();}
 async select(id){const genre=genres.find(g=>g.id===id);if(!genre)return;this.disconnect();this.genre=genre;this.bpm=genre.bpm;this.mode='builtin';await this.start();}
 async load(file){if(!file||file.size>80*1024*1024||(!file.type.startsWith('audio/')&&!/\.(mp3|wav|ogg|m4a|aac|flac|webm)$/i.test(file.name)))throw Error('Choose an audio file smaller than 80 MB.');this.ensure();this.disconnect();this.file=URL.createObjectURL(file);this.media.src=this.file;this.mode='local';this.offset=0;this.label=file.name;try{await this.start();}catch(e){this.disconnect();throw Error('This browser could not play that audio file. Try MP3, WAV or Ogg.');}}
 async microphone(){this.ensure();this.disconnect();if(!navigator.mediaDevices?.getUserMedia)throw Error('Microphone input requires HTTPS and browser support.');const token=++this.generation;await this.ctx.resume();const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});if(token!==this.generation){stream.getTracks().forEach(t=>t.stop());return;}this.stream=stream;this.micSource=this.ctx.createMediaStreamSource(stream);this.micSource.connect(this.analyser);this.mode='mic';this.running=true;this.origin=this.ctx.currentTime;}
 disconnect(){this.pause();this.stream?.getTracks().forEach(t=>t.stop());this.stream=null;this.micSource?.disconnect();this.micSource=null;if(this.file){this.media.removeAttribute('src');this.media.load();URL.revokeObjectURL(this.file);this.file=null;}this.mode='builtin';}
 schedule(){if(!this.running||this.mode!=='builtin')return;let guard=0;while(this.next<this.ctx.currentTime+.13&&guard++<32){if(this.next>=this.ctx.currentTime-.02)this.trigger(this.step,this.next+(this.step%2?this.genre.swing*15/this.bpm:0));this.next+=15/this.bpm;this.step++;}if(this.next<this.ctx.currentTime){this.origin=this.ctx.currentTime+.06;this.next=this.origin;this.step=0;}}
 track(source,end,nodes=[]){this.voices.add(source);source.onended=()=>{source.disconnect();nodes.forEach(n=>n.disconnect());this.voices.delete(source);};source.stop(end);}
 tone(freq,t,duration,type='sine',level=.15,endFreq=null,cutoff=0){const c=this.ctx,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(endFreq)o.frequency.exponentialRampToValueAtTime(endFreq,t+duration*.82);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(level,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+duration);const nodes=[g];if(cutoff){const f=c.createBiquadFilter();f.type='lowpass';f.frequency.setValueAtTime(cutoff,t);f.frequency.exponentialRampToValueAtTime(Math.max(100,cutoff*.35),t+duration);f.Q.value=1.4;o.connect(f).connect(g);nodes.push(f);}else o.connect(g);g.connect(this.bus);o.start(t);this.track(o,t+duration+.02,nodes);}
 noiseHit(t,duration,level,freq,type='highpass'){const c=this.ctx,n=c.createBufferSource(),g=c.createGain(),f=c.createBiquadFilter();n.buffer=this.noise;f.type=type;f.frequency.value=freq;f.Q.value=.65;g.gain.setValueAtTime(level,t);g.gain.exponentialRampToValueAtTime(.0001,t+duration);n.connect(f).connect(g).connect(this.bus);n.start(t);this.track(n,t+duration+.01,[g,f]);}
 trigger(step,t){const g=this.genre,s=step%16,bar=Math.floor(step/16)%16,beat=60/this.bpm,breakdown=bar===7||bar===15;const kick=()=>{this.tone(145,t,.29,'sine',.65,43);this.noiseHit(t,.025,.09,2200);};if(g.kick.includes(s)&&(!breakdown||s<8))kick();if(g.snare.includes(s)){this.noiseHit(t,.15,.30,1550,'highpass');this.tone(180,t,.10,'triangle',.17,100);}if(s%2===0||g.id==='dnb'||g.id==='garage')this.noiseHit(t,s%4===2?.095:.043,(s%2?.018:.045)*(breakdown?.6:1),6800);if((s===14&&bar%4===3)||(g.id==='dnb'&&s===11))this.noiseHit(t,.06,.055,1800);
 const semitones=[0,0,3,-2][Math.floor(bar/4)],freq=440*2**((g.root+semitones-69)/12);if(g.bass.includes(s)&&(!breakdown||s<6)){const interval=(s===13||s===14)?7:0,f=freq*2**(interval/12),dur=beat*(g.id==='140'?.85:.43);this.tone(f,t,dur,'sine',.30);this.tone(f*1.004,t,dur,'sawtooth',.07,null,g.id==='midtempo'?1700:750);this.tone(f*.996,t,dur,'sawtooth',.06,null,650);}
 if([2,10].includes(s)&&(g.id==='house'||g.id==='garage'||bar%4===2)){for(const n of [0,3,7,10]){const f=freq*4*2**(n/12);this.tone(f,t,beat*.35,'triangle',.030);this.tone(f,t+beat*.75,beat*.24,'sine',.010);}}
 if(s%4===0&&bar>=4&&!breakdown){const n=[0,7,10,3][(Math.floor(step/4)+Math.floor(bar/2))%4];this.tone(freq*8*2**(n/12),t,beat*.22,'sine',.023);}
 }
 sample(){if(!this.ctx||!this.running)return {bands:[0,0,0],beat:0,phase:0,freq:null,active:false};this.analyser.getByteFrequencyData(this.freq);const beat=this.mode==='builtin'?Math.max(0,(this.ctx.currentTime-this.origin)*this.bpm/60):this.mode==='local'?Math.max(0,this.media.currentTime-this.offset)*this.bpm/60:Math.max(0,(this.ctx.currentTime-this.origin)*this.bpm/60);return {bands:spectrumBands(this.freq,this.ctx.sampleRate,this.analyser.fftSize),beat,phase:beat%1,freq:this.freq,active:true};}
 async destroy(){this.disconnect();this.mediaSource?.disconnect();await this.ctx?.close();}
}
// Avoid shadowing the AudioContext constructor with the media constructor.
const AudioElement=globalThis.Audio;
